variable "agent_vm_name" { type = string }
variable "location" { type = string }
variable "resource_group_name" { type = string }
variable "admin_username" { type = string }
variable "admin_password" { type = string }
variable "vm_size" { type = string }
variable "agent-vnet" { type = string }
variable "agent-subnet" { type = string }
variable "agentip" { type = string }
variable "agent-nic" { type = string }
variable "nssg" { type = string }
variable "client_secret" {type = string}